# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Base')),
                ('profile_pic', models.URLField(blank=True, default='http://res.cloudinary.com/andela-troupon/image/upload/v1491232845/default_profile_normal_n8yvkf.png')),
                ('about', models.CharField(max_length=20)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.base',),
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='base_ptr',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
