# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='profile_pic',
            field=models.URLField(blank=True, default='http://res.cloudinary.com/andela-troupon/image/upload/v1491232845/default_profile_normal_n8yvkf.png', max_length=255),
        ),
    ]
