# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Base')),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.Profile')),
            ],
            options={
                'ordering': ('date_created',),
            },
            bases=('accounts.base',),
        ),
    ]
