# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_love'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='love',
            unique_together=set([('fan', 'post')]),
        ),
    ]
